---
# https://cspell.org/docs/getting-started/
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'

dictionaryDefinitions:
  - name: custom-words
    path: '~/.vim/configs/cspell-custom_dictionary.txt'
    addWords: true

  - name: program-words
    path: '~/.vim/configs/cspell-program_dictionary.txt'
    addWords: true

dictionaries:
  - bash
  - python
  - custom-words
  - program-words

ignorePaths:
  - 'node_modules'

ignoreRegExpList:
  - "--\\w+"  # ansible-navigator long CLI parameters
