#!/bin/bash

_in_git_repo() {
	if git rev-parse --is-inside-work-tree | grep -q "^true$"; then
		return 0
	fi

	return 1
} # _in_git_repo()

is_git_root() {
	local git_root_dir

	git_root_dir="$(git rev-parse --show-toplevel)"

	if ! _in_git_repo; then
		return 1
	fi

	if [[ ${PWD} == "${git_root_dir}" ]]; then
		return 0
	fi

	return 1
} # is_git_root()()

if ! is_git_root; then
	exit 0
fi

ctags --exclude="@${MYVIMDIR:=${HOME}}/.vim/.ctagsignore" -R . 2>/dev/null
