#!/bin/bash

declare output_cmd="cat"

declare -a targets=("${@:-.}")

show_output() {
	# shellcheck disable=SC2086
	eval ${output_cmd}
} # show_output()

main() {
	time {
		echo gofmt "${targets[@]}"
		time gofmt "${targets[@]}"
		printf "\n"

		echo goimports -w "${targets[@]}"
		time goimports -w "${targets[@]}"
		printf "\n"

		echo golines -w "${targets[@]}"
		time golines -w "${targets[@]}"
		printf "\n"

		echo gofumpt -w "${targets[@]}"
		time gofumpt -w "${targets[@]}"
		printf "\n"
	}
} # main()

vim_stdio() {
	goimports | golines | gofumpt
} # vim_stdio()

if [[ ${1} == --vim ]]; then
	vim_stdio
else
	main |& show_output
fi
