#!/usr/bin/env bash

if [[ ${1} == "lsp" ]]; then
	if [[ ! -d ${MYVIMDIR:=${HOME}}/git_remote/java-language-server ]]; then
		git clone https://github.com/georgewfraser/java-language-server "${MYVIMDIR:=${HOME}}/git_remote/java-language-server"

		cd "${MYVIMDIR:=${HOME}}/git_remote/java-language-server" || exit

		./scripts/link_linux.sh

		mvn package -DskipTests
	fi

	cd "${MYVIMDIR:=${HOME}}/git_remote/java-language-server" || exit

	exec "./dist/lang_server_linux.sh" "${@}"
fi

if [[ ! -d ${MYVIMDIR:=${HOME}}/git_remote/eclipse.jdt.ls ]]; then
	git clone https://github.com/eclipse-jdtls/eclipse.jdt.ls "${MYVIMDIR:=${HOME}}/git_remote/eclipse.jdt.ls"

	cd "${MYVIMDIR:=${HOME}}/git_remote/eclipse.jdt.ls" || exit

	time ./mvnw clean verify
fi

cd "${MYVIMDIR:=${HOME}}/git_remote/eclipse.jdt.ls" || exit

# exec "./org.eclipse.jdt.ls.product/target/repository/bin/jdtls" "${@}"

declare -a jars=(./org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_*.jar)

# https://projectlombok.org/downloads/lombok.jar
if [[ ! -f ${MYVIMDIR:=${HOME}}/.config/lombok/lombok.jar ]]; then
	mkdir -pv "${MYVIMDIR:=${HOME}}"/.config/lombok/
	curl -sSL https://projectlombok.org/downloads/lombok.jar >"${MYVIMDIR:=${HOME}}"/.config/lombok/lombok.jar
fi

exec java \
	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
	-Dosgi.bundles.defaultStartLevel=4 \
	-Declipse.product=org.eclipse.jdt.ls.core.product \
	-Dlog.protocol=true \
	-Dlog.level=ALL \
	-Xms1g \
	-Xmx2G \
	-javaagent:"${MYVIMDIR:=${HOME}}"/.config/lombok/lombok.jar \
	-Xbootclasspath/a:"${MYVIMDIR:=${HOME}}"/.config/lombok/lombok.jar \
	-jar "${jars[*]}" \
	-configuration "./org.eclipse.jdt.ls.product/target/repository/config_linux/" \
	-data "${1}" \
	--add-modules=ALL-SYSTEM \
	--add-opens java.base/java.util=ALL-UNNAMED \
	--add-opens java.base/java.lang=ALL-UNNAMED
