#!/usr/bin/env bash

set -e

#if [[ -d .venv ]]; then
## shellcheck disable=SC1091
#source ./.venv/bin/activate
#fi

if [[ -f .pdm-python ]]; then
	exec pdm run jedi-language-server "${@}"
else
	exec jedi-language-server "${@}"
fi
