#!/bin/bash

declare output_cmd="cat"

declare -a targets=("${@:-.}")

show_output() {
	# shellcheck disable=SC2086
	eval ${output_cmd}
} # show_output()

main() {
	time {
		echo autopep8 --in-place --recursive "${targets[@]}"
		time autopep8 --in-place --recursive "${targets[@]}"
		printf "\n"

		echo yapf --style=google --recursive --in-place "${targets[@]}"
		time yapf --style=google --recursive --in-place "${targets[@]}"
		printf "\n"

		echo isort --profile black --dont-follow-links --atomic --ensure-newline-before-comments "${targets[@]}"
		time isort --profile black --dont-follow-links --atomic --ensure-newline-before-comments "${targets[@]}"
		printf "\n"

		echo black --line-length=240 "${targets[@]}"
		time black --line-length=240 "${targets[@]}"
		printf "\n"
	}
} # main()

vim_stdio() {
	isort --profile black --ensure-newline-before-comments --stdout - | black --line-length=240 -
} # vim_stdio()

if [[ ${1} == --vim ]]; then
	vim_stdio
else
	main |& show_output
fi
