#!/usr/bin/env bash

set -e

#if [[ -d .venv ]]; then
## shellcheck disable=SC1091
#source ./.venv/bin/activate
#fi

if [[ -f .pdm-python ]]; then
	exec pdm run ruff-lsp "${@}"
else
	exec ruff-lsp "${@}"
fi
