#!/bin/bash

time while read -r line; do
        echo npm update --global "${line}"
        time npm update --global "${line}"
        printf "\n"
done <"${MYVIMDIR:=${HOME}}"/.vim/requirements-npm.txt
